### ISSUE TITLE
请问考试会不会检测页面上是否有中文？

### ISSUE THREAD

**Issue by darriousliu** [simonkimi/TampermonkeyScripts#1]
或者说是会不会把整个页面截图上传？

**Comment by simonkimi** [comment]
目前JS没有任何命令能对网页进行截图, 如果有, 我有个项目开发应该会变简单点.
判断中文的可能性不大, 因为不少文章都自带中文来着

**Comment by darriousliu** [comment]
考试好像是弹出来一个窗口，是不是把里面网址复制出来新开一个窗口就能使用这个脚本了？

**Comment by darriousliu** [comment]
我在叉子网上看的另一个脚本评论说打开考试界面好像会冲突，commit里面有个解决冲突，不知道是不是解决的这个问题

**Comment by simonkimi** [comment]
独立窗口也可以使用, 那个脚本的作者是我同学, 并不是解决这个问题的

**Comment by darriousliu** [comment]
那这个冲突的话不就就用不了了(ㄒoㄒ)

**Comment by simonkimi** [comment]
单独弹窗不影响使用, 说了多少遍了

**Comment by darriousliu** [comment]
好吧，谢谢了
