### ISSUE TITLE
itest是否可以侦测到删除了事件

### ISSUE THREAD

**Issue by slightin** [simonkimi/TampermonkeyScripts#10]
如果我在事件侦听器中删除了blur和focus事件，itest会不会检测到

**Comment by simonkimi** [comment]
最好不要删除, 置空即可

**Comment by slightin** [comment]
请问大佬如何置空

**Comment by simonkimi** [comment]
改成一个空函数

**Comment by slightin** [comment]
函数体是onblur和onfocus吗

**Comment by slightin** [comment]
我把onblur和onfocus函数变成空函数之后还是会监测到切屏

**Comment by simonkimi** [comment]
一个是, 你必须保证在paper-answer.js加载之后再置空
第二个是, 你不能在考试中用F12把onfocus置空, 否则系统无法检测你切回来了

**Comment by slightin** [comment]
请问大佬有什么处理方法吗

**Comment by simonkimi** [comment]
我代码里已经有了, 油猴延迟5秒执行, 并每5秒执行一次

**Comment by slightin** [comment]
请问大佬相关代码在那几行呢，我还没学HTML，实在是找不到

**Comment by slightin** [comment]
``(async () => {  
    'use strict';  
        setInterval(function () {  
            if (window.onblur !== null) {  
                window.onblur = null;  
            }  
            if (window.onfocus !== null) {  
                window.onfocus = null;  
            }  
        }, 5 * 1000)  
})()``
这样是否可以呢

**Comment by slightin** [comment]
我把这段代码放到了油猴脚本，然后在你的测试网页里测试了一下，发现事件侦听器那里没有了blur和focus事件

**Comment by slightin** [comment]
unload事件是什么，置空后我发现触发了unload事件

**Comment by slightin** [comment]
![批注 2020-07-02 233442](https://user-images.githubusercontent.com/67229521/86378810-a701ad80-bcbc-11ea-86d7-fe95e67e8a43.jpg)
