### ISSUE TITLE
111

### ISSUE THREAD

**Issue by lananz** [simonkimi/TampermonkeyScripts#2]
itest脚本开下来只能翻译题目 听力没有那个进度条 文章都翻译不了

**Comment by simonkimi** [comment]
因为缺少样本, 我只能适配我所经历的那场考试, 如果方便的话, 可以把考试的html另存下来, 我将会尝试进行适配

**Comment by yan259128** [comment]
大佬

**Comment by yan259128** [comment]
求更新啊，脚本用不了了
明天就要考试了
