### ISSUE TITLE
求更新啊，Tamper monkey上的脚本删除了，我复制代码也用不了了

### ISSUE THREAD

**Issue by yan259128** [simonkimi/TampermonkeyScripts#4]

**Comment by yan259128** [comment]
我把代码改动之后，那个可以多次听听力了，但是在考试页面用不了翻译功能，在进入考试前的那几个核对个人信息，键盘检测和耳机检测的这三个页面可以用，但是进入考试答题页面之后就用不了，求解决。至于改动的代码就是把判断是否为iTEST平台的代码给删除了，还有接收判断结果的语句也删除了。

**Comment by simonkimi** [comment]
我看了下代码, 新版大概时这样:
1. 拦截了ajax代码, 无法请求翻译, 发现翻译api判定为作弊
2. 检测右键菜单, 有右键菜单判定为作弊
只要解决这两个问题就可以继续使用脚本了

**Comment by yan259128** [comment]
我只学过c++语言，对这些不懂啊，麻烦大佬给更新下
我明天就要考试，谢谢大佬了

**Comment by yan259128** [comment]
突然发现，刚进入考试的前几秒可以用翻译，但是只能用一次

**Comment by simonkimi** [comment]
千万不要在正式考试使用, 因为检测了ajax, 发现翻译api就就会判定你作弊

**Comment by yan259128** [comment]
我在一个模拟考试里试脚本

**Comment by yan259128** [comment]
那大佬能改进么？

**Comment by simonkimi** [comment]
我已经改好, 但是由于法律问题无法公开

**Comment by yan259128** [comment]
那大佬私发给我咯。谢谢了

**Comment by yan259128** [comment]
可以么？

**Comment by yan259128** [comment]
q 2591284724

**Comment by yan259128** [comment]
求发，谢谢

**Comment by yan259128** [comment]
大佬还在不？

**Comment by yan259128** [comment]
别关了啊

**Comment by yan259128** [comment]
大佬，可以有偿啊
